### ISSUE TITLE
Long application sections break display

### ISSUE THREAD

**Issue by greigm** [noelzubin/crib#4]
Example bindings.yaml:

```

- name: app
  bindings:
  - name: Some function with a longer description causing wrapping 1
    key: 1
  - name: Some function with a longer description causing wrapping 2
    key: 2
  - name: Some function with a longer description causing wrapping 3
    key: 3
  - name: Some function with a longer description causing wrapping 4
    key: 4
  - name: Some function with a longer description causing wrapping 5
    key: 5
  - name: Some function with a longer description causing wrapping 6
    key: 6
  - name: Some function with a longer description causing wrapping 7
    key: 7
  - name: Some function with a longer description causing wrapping 8
    key: 8
  - name: Some function with a longer description causing wrapping 9
    key: 9
  - name: Some function with a longer description causing wrapping 10
    key: 10
  - name: Some function with a longer description causing wrapping 11
    key: 11
  - name: Some function with a longer description causing wrapping 12
    key: 12
  - name: Some function with a longer description causing wrapping 13
    key: 13
  - name: Some function with a longer description causing wrapping 14
    key: 14
  - name: Some function with a longer description causing wrapping 15
    key: 15
  - name: Some function with a longer description causing wrapping 16
    key: 16
  - name: Some function with a longer description causing wrapping 17
    key: 17
  - name: Some function with a longer description causing wrapping 18
    key: 18
  - name: Some function with a longer description causing wrapping 19
    key: 19
  - name: Some function with a longer description causing wrapping 20
    key: 20

```

Running `crib` or `crib app` with this file simply results in `Search:` or `Search: app:` in the latter case.
`crib app --print` results in a single blank line.

Trimming the file to use short names - ie "Some function 1" works as expected. As does reducing the number of lines to 14. Increasing the terminal size allows an extra line at the threshold - ie. if 13 was the limit, and I stretch the terminal by an extra couple rows, I get 14 keys displayed before it fails. This may be by design, but it definitely limits the usefulness for me, and is also confusing when it doesn't even give an "input too long" or similar error.
